export const TIMEZONE_OPTIONS = [
	{ value: "-12", label: "UTC−12" },
	{ value: "-11", label: "UTC−11" },
	{ value: "-10", label: "UTC−10 (Havaí)" },
	{ value: "-9.5", label: "UTC−9:30" },
	{ value: "-9", label: "UTC−9 (Alasca)" },
	{ value: "-8", label: "UTC−8 (Los Angeles)" },
	{ value: "-7", label: "UTC−7 (Denver)" },
	{ value: "-6", label: "UTC−6 (Cidade do México)" },
	{ value: "-5", label: "UTC−5 (Nova York)" },
	{ value: "-4", label: "UTC−4 (Manaus)" },
	{ value: "-3", label: "UTC−3 (Brasília)" },
	{ value: "-2", label: "UTC−2 (Fernando de Noronha)" },
	{ value: "-1", label: "UTC−1 (Açores)" },
	{ value: "0", label: "UTC±0 (Londres)" },
	{ value: "1", label: "UTC+1 (Paris)" },
	{ value: "2", label: "UTC+2 (Cairo)" },
	{ value: "3", label: "UTC+3 (Moscou)" },
	{ value: "3.5", label: "UTC+3:30 (Teerã)" },
	{ value: "4", label: "UTC+4 (Dubai)" },
	{ value: "4.5", label: "UTC+4:30 (Cabul)" },
	{ value: "5", label: "UTC+5 (Paquistão)" },
	{ value: "5.5", label: "UTC+5:30 (Índia)" },
	{ value: "5.75", label: "UTC+5:45 (Nepal)" },
	{ value: "6", label: "UTC+6 (Bangladesh)" },
	{ value: "6.5", label: "UTC+6:30 (Myanmar)" },
	{ value: "7", label: "UTC+7 (Bangkok)" },
	{ value: "8", label: "UTC+8 (Pequim)" },
	{ value: "8.75", label: "UTC+8:45" },
	{ value: "9", label: "UTC+9 (Tóquio)" },
	{ value: "9.5", label: "UTC+9:30 (Adelaide)" },
	{ value: "10", label: "UTC+10 (Sydney)" },
	{ value: "10.5", label: "UTC+10:30" },
	{ value: "11", label: "UTC+11" },
	{ value: "12", label: "UTC+12 (Auckland)" },
	{ value: "12.75", label: "UTC+12:45" },
	{ value: "13", label: "UTC+13 (Tonga)" },
	{ value: "14", label: "UTC+14" },
];
